#if !defined(AFX_LIGHTNINGALARM_H__83F6CFD7_F4CF_4335_B612_BFB8EC6AF08F__INCLUDED_)
#define AFX_LIGHTNINGALARM_H__83F6CFD7_F4CF_4335_B612_BFB8EC6AF08F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLightningAlarm wrapper class

class CLightningAlarm : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLightningAlarm)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x73861100, 0xd037, 0x4ef3, { 0x8e, 0xb5, 0x62, 0xa8, 0x3a, 0x22, 0xec, 0xc9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetColourControlBackground(unsigned long newColour);
	void SetColourRingBorder(unsigned long newColour);
	void SetHighFieldAlarm(long bActive);
	void SetVeryHighFieldAlarm(long bActive);
	void SetLightningAlarm(long bActive, double dDistance);
	void SetDistanceRings(double* pdRingDef, short sRingCount);
	void SetEnabled(long bEnabled);
	void SetUnitText(LPCTSTR szUnitText);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LIGHTNINGALARM_H__83F6CFD7_F4CF_4335_B612_BFB8EC6AF08F__INCLUDED_)
