#if !defined(AFX_NUMLED_H__58DA4AB0_1A95_454E_BD53_221D2FDC1C69__INCLUDED_)
#define AFX_NUMLED_H__58DA4AB0_1A95_454E_BD53_221D2FDC1C69__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CNumLED wrapper class

class CNumLED : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNumLED)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa68a1583, 0x4572, 0x11d0, { 0xb5, 0x97, 0x0, 0xa0, 0x24, 0xa5, 0x4a, 0x93 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetDigits();
	void SetDigits(short);
	short GetDecimals();
	void SetDecimals(short);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	CPicture GetBackPicture();
	void SetBackPicture(LPDISPATCH);
	long GetBevelInner();
	void SetBevelInner(long);
	long GetBevelOuter();
	void SetBevelOuter(long);
	unsigned long GetOnColor();
	void SetOnColor(unsigned long);
	unsigned long GetOffColor();
	void SetOffColor(unsigned long);
	double GetValue();
	void SetValue(double);
	double Get_Value();
	void Set_Value(double);
	short GetBevelWidth();
	void SetBevelWidth(short);
	short GetBorderWidth();
	void SetBorderWidth(short);
	BOOL GetLeadingZeros();
	void SetLeadingZeros(BOOL);
	short GetSpacingHorizontal();
	void SetSpacingHorizontal(short);
	short GetSpacingVertical();
	void SetSpacingVertical(short);
	BOOL GetFixedDecimal();
	void SetFixedDecimal(BOOL);
	short GetItalicsOffset();
	void SetItalicsOffset(short);
	short GetSegmentWidth();
	void SetSegmentWidth(short);
	short GetSegmentSeparation();
	void SetSegmentSeparation(short);
	BOOL GetLeadingOneDigit();
	void SetLeadingOneDigit(BOOL);
	long GetDisplayMode();
	void SetDisplayMode(long);
	short GetDecimalSize();
	void SetDecimalSize(short);
	short GetDecimalPosition();
	void SetDecimalPosition(short);
	BOOL GetLeadingPlusMinus();
	void SetLeadingPlusMinus(BOOL);
	CString GetAlphaNumeric();
	void SetAlphaNumeric(LPCTSTR);
	BOOL GetOutline();
	void SetOutline(BOOL);
	long GetOutlineAlign();
	void SetOutlineAlign(long);
	unsigned long GetOutlineColor();
	void SetOutlineColor(unsigned long);
	CString GetOutlineTitle();
	void SetOutlineTitle(LPCTSTR);
	short GetOutlineWidth();
	void SetOutlineWidth(short);
	BOOL GetSingleBuffer();
	void SetSingleBuffer(BOOL);
	BOOL GetFocusOutline();
	void SetFocusOutline(BOOL);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	CString GetConfiguration();
	void SetConfiguration(LPCTSTR);
	BOOL GetAutoRedraw();
	void SetAutoRedraw(BOOL);

// Operations
public:
	void ShowPropertyPage();
	void Redraw();
	void RedrawStatic();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NUMLED_H__58DA4AB0_1A95_454E_BD53_221D2FDC1C69__INCLUDED_)
