//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EFM.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX_BOLTEK             100
#define IDS_ABOUTBOX                    101
#define IDD_EFM_DIALOG                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define STR_ROTORFAULT_WAV              104
#define STR_SIGNALLOSTFAULT_WAV         105
#define WM_FIELDMILLDATA                106
#define STR_LIGHTNINGDETECTED_WAV       106
#define WM_CLIENTDATA                   107
#define STR_HIGHELECTRICFIELD_WAV       107
#define WM_CLIENTCLOSING                108
#define STR_VERYHIGHELECTRICFIELD_WAV   108
#define STR_STARTUP_WAV                 109
#define WM_PROGRAMSHUTDOWN              110
#define STR_EVENTLOGFILENAME            110
#define WM_REMOTECONNECTIONCLOSED       111
#define STR_SOURCEPOINT_SERIAL          111
#define STR_SOURCEPOINT_NETWORK         112
#define WM_CONNECTIONFAILURE            113
#define STR_SOURCEPOINT_LWS200          113
#define WM_CONNECTIONSUCCESSFUL         114
#define STR_SOURCEPOINT_LWS300          114
#define WM_ROTORFAULT                   115
#define STR_SOURCEPOINT_EFA20           115
#define WM_SELFTESTFAULT                116
#define STR_USBIDENT_EFA20              116
#define WM_LIGHTNINGALARM               117
#define WM_VERYHIGHFIELDALARM           118
#define WM_HIGHFIELDALARM               119
#define WM_NOALARMS                     120
#define WM_SIGNALLOSTFAULT              121
#define STR_TWILIO_ACCOUNT_SID          122
#define STR_TWILIO_AUTH_TOKEN           123
#define STR_TWILIO_PHONE_NUMBER         124
#define WM_EVERYTHINGNOMINAL            126
#define WM_SETCONTROLCOLOURS            127
#define IDR_MAINFRAME                   128
#define IDD_OPTIONS                     129
#define IDR_EFMMENU                     130
#define CHARTVIEW_FIELDMILL1            131
#define BMP_OPTIONMENU                  132
#define CHARTVIEW_FIELDMILL2            132
#define CHARTVIEW_FIELDMILL3            133
#define BMP_BOLTEKLOGO                  134
#define CHARTVIEW_FIELDMILL4            134
#define IDD_OPTIONS_GENERAL             135
#define IDD_OPTIONS_SOUND               136
#define BMP_FOLDER                      137
#define BMP_PLAY                        138
#define IDD_OPTIONS_ALARMS              139
#define IDD_OPTIONS_DATALOGGING         140
#define BMP_STOP                        141
#define IDD_OPTIONS_IMAGECAPTURE        142
#define IDD_OPTIONS_DATASHARING         143
#define IDD_WAITDLG                     148
#define IDD_EVENTLOG                    150
#define IDD_ADDREMOVERINGS              153
#define CHARTVIEW_FIELDMILL5            154
#define CHARTVIEW_FIELDMILL6            155
#define CHARTVIEW_FIELDMILL7            156
#define CHARTVIEW_FIELDMILL8            157
#define IDR_VIEWEVENTLOG                160
#define IDD_OPTIONS_HIGHFIELDALARM      161
#define IDD_OPTIONS_VERYHIGHFIELDALARM  162
#define IDD_OPTIONS_LIGHTNINGALARM      163
#define IDD_DEBUGGER                    167
#define IDB_BRIGHTEX_LOGO               168
#define IDD_ABOUTBOX_BRIGHTEX           168
#define IDI_BRIGHTEX                    169
#define IDB_BRIGHTEX_LOGO2              171
#define IDD_OPTIONS_DELTAALARM          172
#define IDD_OPTIONS_ALERTS              176
#define BMP_PEOPLE                      178
#define BMP_CONFIGURE                   179
#define IDD_CONFIGUREEMAILSERVER        180
#define IDD_CONFIGUREGSMMODEM           181
#define IDD_EMAILRECIPIENTS             182
#define IDD_SMSRECIPIENTS               183
#define IDD_ADDEDITRECIPIENT            184
#define IDD_CONFIGUREGSMGATEWAY         185
#define IDD_EVENTLOG1                   186
#define IDD_SHOWCONNECTED               186
#define IDD_CLIENTSCONNECTEDVIEWER      186
#define BTN_ACCEPT                      1000
#define BTN_CANCEL                      1001
#define LST_OPTIONS                     1003
#define TAB_GENERAL                     1008
#define SPIN_NUMOFDATASOURCES           1016
#define LBL_NUMOFDATASOURCES            1017
#define LBL_MAXSOURCES                  1023
#define CHK_LA_BEEP                     1026
#define CHK_LA_WAV                      1027
#define CHK_LA_ONACTIVATIONWAV          1027
#define SLD_LA_BEEPPITCH                1028
#define CHK_LA_WAV2                     1028
#define CHK_LA_DISTANCEWAV              1028
#define SLD_LA_BEEPTIMEOFF              1029
#define CHK_LA_WAV3                     1029
#define CHK_LA_REPEATWAV                1029
#define SLD_LA_BEEPTIMEON               1030
#define CHK_LA_WAV4                     1030
#define CHK_LA_ALLCLEARWAV              1030
#define TXT_LA_WAVFILE                  1031
#define TXT_LA_ONACTIVATIONWAVFILE      1031
#define BTN_CHOOSEWAV                   1032
#define BTN_CHOOSEWAV_ONACTIVATION      1032
#define TXT_LA_WAVFILE2                 1033
#define TXT_LA_DISTANCEWAVFILES         1033
#define BTN_CHOOSEWAV2                  1034
#define BTN_CHOOSEWAV_DISTANCE          1034
#define TXT_LA_WAVFILE3                 1035
#define TXT_LA_REPEATWAVFILE            1035
#define BTN_CHOOSEWAV3                  1036
#define BTN_CHOOSEWAV_REPEAT            1036
#define TXT_LA_WAVFILE4                 1037
#define TXT_LA_ALLCLEARWAVFILE          1037
#define BTN_CHOOSEWAV4                  1038
#define BTN_CHOOSEWAV_ALLCLEAR          1038
#define LBL_LA_BEEPPITCH                1045
#define LBL_LA_BEEPTIMEON               1046
#define LBL_LA_BEEPTIMEOFF              1047
#define CHK_HFA_BEEP                    1048
#define CHK_HFA_WAV                     1049
#define SLD_HFA_BEEPPITCH               1050
#define SLD_HFA_BEEPTIMEOFF             1051
#define SLD_HFA_BEEPTIMEON              1052
#define LBL_HFA_BEEPPITCH               1053
#define LBL_HFA_BEEPTIMEON              1054
#define LBL_HFA_BEEPTIMEOFF             1055
#define TXT_HFA_WAVFILE                 1056
#define BTN_HFA_CHOOSEWAV               1057
#define CHK_VHFA_BEEP                   1058
#define CHK_VHFA_WAV                    1059
#define SLD_VHFA_BEEPPITCH              1060
#define SLD_VHFA_BEEPTIMEOFF            1061
#define SLD_VHFA_BEEPTIMEON             1062
#define LBL_VHFA_BEEPPITCH              1063
#define LBL_VHFA_BEEPTIMEON             1064
#define LBL_VHFA_BEEPTIMEOFF            1065
#define TXT_VHFA_WAVFILE                1066
#define BTN_VHFA_CHOOSEWAV              1067
#define BTN_LA_PLAYBEEP                 1068
#define BTN_LA_PLAYWAV                  1069
#define BTN_PLAYWAV_ONACTIVATION        1069
#define BTN_HFA_PLAYBEEP                1070
#define BTN_LA_PLAYWAV2                 1070
#define BTN_PLAYWAV_DISTANCE            1070
#define BTN_HFA_PLAYWAV                 1071
#define CMB_DATASOURCENAMES             1071
#define BTN_VHFA_PLAYBEEP               1072
#define BTN_LA_PLAYWAV3                 1072
#define BTN_PLAYWAV_REPEAT              1072
#define BTN_VHFA_PLAYWAV                1073
#define CHK_ENABLEHFA                   1073
#define CHK_ENABLELA                    1073
#define CHK_ENABLEVHFA                  1074
#define BTN_LA_PLAYWAV4                 1074
#define CMB_HFA_DATASOURCENAMES         1074
#define BTN_PLAYWAV_ALLCLEAR            1074
#define TXT_LA_DURATION                 1075
#define CMB_VHFA_DATASOURCENAMES        1075
#define CHK_ENABLESETPOINTONGRAPH       1075
#define TXT_HFA_SETPOINT                1076
#define CHK_ONLYANNOUNCECLOSER          1076
#define CHK_ENABLEVHFASETPOINTONGRAPH   1076
#define TXT_HFA_DURATION                1077
#define CMB_DATASOURCEPOINT             1077
#define CHK_ENABLECHARTLA               1077
#define CHK_SHOWCHARTLA                 1077
#define TXT_VHFA_SETPOINT               1078
#define TXT_DATASOURCENAME              1078
#define TXT_VHFA_DURATION               1079
#define CMB_DATASOURCES                 1080
#define CMB_COMPORT                     1082
#define IPA_NETWORKIP                   1083
#define CMB_COMPORT2                    1083
#define TXT_NETWORKPORT                 1084
#define CHK_ENABLEDATALOGGING           1085
#define CMB_DL_DATASOURCES              1087
#define TXT_LOGLOCATION                 1088
#define BTN_LOGLOCATION                 1090
#define CHK_DATASOURCEENABLED           1095
#define STRIP_FIELDMILL1                1100
#define STRIP_FIELDMILL2                1101
#define STRIP_FIELDMILL3                1102
#define STRIP_FIELDMILL4                1103
#define KNOB_SCALESELECTOR              1104
#define KNOB_TIMESELECTOR               1105
#define NUMLED_FIELDMILL1               1106
#define NUMLED_FIELDMILL2               1107
#define NUMLED_FIELDMILL3               1108
#define NUMLED_FIELDMILL4               1109
#define LBL_WAITTEXT                    1116
#define LBL_WAITSUBTEXT                 1117
#define LBL_L_FIELDMILL1                1118
#define LBL_L_FIELDMILL2                1119
#define LBL_L_FIELDMILL3                1120
#define LBL_L_FIELDMILL4                1121
#define LBL_HF_FIELDMILL1               1122
#define LBL_HF_FIELDMILL2               1123
#define LBL_HF_FIELDMILL3               1124
#define LBL_HF_FIELDMILL4               1125
#define LBL_VHF_FIELDMILL1              1126
#define LBL_VHF_FIELDMILL2              1127
#define LBL_VHF_FIELDMILL3              1128
#define LBL_VHF_FIELDMILL4              1129
#define LBL_SENSITIVITY                 1133
#define TXT_LAMAGNITUDE                 1134
#define TXT_LASENSITIVITY               1134
#define TXT_LISTENPORT                  1136
#define LBL_LISTENPORT                  1137
#define CHK_ENABLESHARING               1138
#define TXT_NETWORKADDRESS              1139
#define TXT_LA_WAVREPEATINTERVAL        1140
#define TXT_VHFA_WAVREPEATINTERVAL      1141
#define BTN_CLOSE                       1141
#define TXT_HFA_WAVREPEATINTERVAL       1142
#define BTN_CLEARLOGFILE                1142
#define LST_EVENTS                      1143
#define BTN_REFRESHLOG                  1144
#define TXT_RAINNOISEFILTER             1145
#define TXT_VHFA_DELAY                  1146
#define TXT_HFA_DELAY                   1147
#define LBL_VERSION                     1147
#define LBL_STATUS_FIELDMILL1           1148
#define LBL_STATUS_FIELDMILL2           1149
#define LBL_STATUS_FIELDMILL3           1150
#define LBL_STATUS_FIELDMILL4           1151
#define TGL_MUTESOUND_FIELDMILL1        1152
#define TGL_MUTESOUND_FIELDMILL2        1153
#define TGL_MUTESOUND_FIELDMILL3        1154
#define TGL_MUTESOUND_FIELDMILL4        1155
#define PCT_HF_FIELDMILL1               1156
#define PCT_HF_FIELDMILL2               1157
#define PCT_HF_FIELDMILL3               1158
#define PCT_HF_FIELDMILL4               1159
#define PCT_VHF_FIELDMILL1              1160
#define CHK_HIGHRESOLUTION              1160
#define PCT_VHF_FIELDMILL2              1161
#define IDC_SEPARATOR                   1161
#define PCT_VHF_FIELDMILL3              1162
#define PCT_VHF_FIELDMILL4              1163
#define PCT_L_FIELDMILL1                1164
#define PCT_L_FIELDMILL2                1165
#define PCT_L_FIELDMILL3                1166
#define PCT_L_FIELDMILL4                1167
#define PCT_STATUS_FIELDMILL1           1168
#define PCT_STATUS_FIELDMILL2           1169
#define PCT_STATUS_FIELDMILL3           1170
#define PCT_STATUS_FIELDMILL4           1171
#define PCT_DELTA_FIELDMILL1            1172
#define PCT_DELTA_FIELDMILL2            1173
#define PCT_DELTA_FIELDMILL3            1174
#define PCT_DELTA_FIELDMILL4            1175
#define LALARM_FIELDMILL1               1176
#define LALARM_FIELDMILL2               1177
#define LALARM_FIELDMILL3               1178
#define LALARM_FIELDMILL4               1179
#define RDO_LA_UNIT                     1182
#define RDO_LA_UNIT_KM                  1183
#define BTN_LARINGS_ADD                 1185
#define BTN_LARINGS_REMOVE              1186
#define LBL_LA_RINGS                    1187
#define TXT_ADDREMOVEVALUE              1188
#define LBL_ADDREMOVETEXT               1189
#define IDC_PERCENTCTRL2                1191
#define IDC_PERCENTCTRL4                1193
#define IDC_PERCENTCTRL5                1194
#define LBL_COMPANYNAME                 1196
#define LBL_COPYRIGHT                   1197
#define LBL_SOFTWAREDESCRIPTION         1198
#define LBL_SAFETYWARNING               1199
#define SB_LOGPOSITION                  1200
#define LBL_DISTANCEUNIT                1203
#define IDC_CHECK1                      1204
#define CMB_LA_DATASOURCENAMES          1205
#define LST_CONNECTEDCLIENTS            1206
#define LBL_CONNECTEDCLIENTCOUNT        1207
#define CMB_DA_DATASOURCENAMES          1209
#define CHK_ENABLEDA                    1210
#define TXT_DA_SETPOINT                 1211
#define TXT_DA_INTERVAL                 1212
#define TXT_DA_DURATION                 1213
#define CHK_DA_WAV                      1214
#define TXT_DA_WAVFILE                  1215
#define BTN_DA_CHOOSEWAV                1216
#define BTN_DA_PLAYWAV                  1217
#define TXT_DA_WAVREPEATINTERVAL        1218
#define TXT_DA_DELAY                    1219
#define CMB_COINCIDENCE_DETECTION       1220
#define CMB_COINCIDENCE_COMPORT         1221
#define CMB_EFA20SERIALNUMBER           1222
#define BTN_SMSCONFIGURE                1226
#define BTN_SMSCONFIGURE2               1227
#define BTN_EMAILCONFIGURE              1232
#define CHK_EMAILALERT                  1233
#define CHK_SMSALERT                    1234
#define CHK_SMSGSMALERT                 1234
#define IDC_CHECK8                      1235
#define CHK_LA_ACTIVE                   1235
#define IDC_CHECK9                      1236
#define CHK_LA_CLEAR                    1236
#define IDC_CHECK10                     1237
#define CHK_HF_ACTIVE                   1237
#define IDC_CHECK11                     1238
#define CHK_HF_CLEAR                    1238
#define IDC_CHECK12                     1239
#define CHK_FAULTS_ACTIVE               1239
#define IDC_CHECK13                     1240
#define CHK_FAULTS_CLEAR                1240
#define IDC_CHECK14                     1241
#define CHK_VHF_ACTIVE                  1241
#define IDC_CHECK15                     1242
#define CHK_VHF_CLEAR                   1242
#define IDC_CHECK16                     1243
#define CHK_DA_ACTIVE                   1243
#define IDC_CHECK17                     1244
#define CHK_DA_CLEAR                    1244
#define BTN_EMAILRECIPIENTS             1245
#define CHK_SMSGATEWAYALERT             1245
#define BTN_SMSRECIPIENTS               1246
#define CHK_SCHEDULED                   1246
#define IDC_LIST2                       1248
#define LBL_EMAILSERVER                 1249
#define LBL_SMTPSERVER                  1249
#define LBL_SMSGSMMODEM                 1250
#define IDC_RADIO1                      1251
#define LBL_SMSGATEWAY                  1251
#define IDC_SECURITYTYPE1               1251
#define IDC_RADIOCLICKATELL             1251
#define IDC_RADIO2                      1252
#define IDC_SECURITYTYPE2               1252
#define IDC_RADIOTWILIO                 1252
#define IDC_RADIO3                      1253
#define IDC_SECURITYTYPE3               1253
#define IDC_EDIT1                       1254
#define IDC_EDIT2                       1255
#define IDC_USERNAME                    1255
#define IDC_EDIT3                       1256
#define IDC_PASSWORD                    1256
#define IDC_EDIT4                       1257
#define IDC_APIID                       1257
#define IDC_EDIT5                       1258
#define IDC_EDIT6                       1259
#define TXT_SMTP_SENDER_EMAIL           1259
#define IDC_BUTTON1                     1260
#define IDC_COMBO1                      1261
#define IDC_COMBO2                      1262
#define IDC_COMBO3                      1263
#define IDC_COMBO4                      1264
#define IDC_LIST1                       1265
#define LST_RECIPIENTS                  1266
#define IDC_BUTTON2                     1267
#define CMB_AL_DATASOURCENAMES          1268
#define IDC_EMAILLIST                   1269
#define IDC_SMSLIST                     1270
#define IDC_ADD_EMAIL                   1271
#define IDC_DELETE_EMAIL                1272
#define IDC_ADD_SMS                     1273
#define LBL_ADDEDITRECIPIENT            1273
#define LBL_ADDEDITRECIPIENT1           1273
#define IDC_DELETE_SMS                  1274
#define TXT_SMTP_SERVER                 1274
#define LBL_ADDEDITRECIPIENT2           1274
#define IDC_EDIT_EMAIL                  1275
#define TXT_SERVER_PORT                 1275
#define IDC_EDIT_SMS                    1276
#define TXT_SMTP_USERNAME               1276
#define TXT_SMTP_PASSWORD               1277
#define TXT_SMTP_SENDER_NAME            1278
#define IDC_EMAILTEST                   1280
#define IDC_SMSGSMTEST                  1281
#define IDC_MODEMINIT                   1281
#define IDC_SMSGATEWAYTEST              1282
#define IDC_BAUDRATE                    1282
#define IDC_SCHEDULEDTIMEPICKER         1283
#define IDC_FIRMWARE_VERSION            1284
#define IDC_STATIC_USERNAME             1285
#define IDC_STATIC_PASSWORD             1286
#define IDC_STATIC_API_ID               1287
#define STR_CLICK_A_TELL_USERNAME       1288
#define STR_CLICK_A_TELL_PASSWORD       1289
#define STR_CLICK_A_TELL_API_ID         1290
#define MNU_FILE_EXIT                   32771
#define STR_PROGRAMEXITQUESTION         32772
#define MNU_OPTIONS                     32772
#define STR_PROGRAMEXITQUESTIONTITLE    32773
#define MNU_HELP_ABOUT                  32773
#define MNU_TOOLS_FULLSCREEN            32775
#define MNU_TOOLS_OPTIONS               32776
#define MNU_FILE_OPEN                   32777
#define MNU_FILE_VIEWEVENTLOG           32778
#define MNU_TOOLS_SHOWCONNECTEDCLIENTS  32779
#define MSG_LINEUP                      32780
#define MSG_LINEDOWN                    32781
#define MSG_PAGEUP                      32782
#define MSG_PAGEDOWN                    32783
#define MSG_HEAD                        32784
#define MSG_TAIL                        32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1288
#define _APS_NEXT_SYMED_VALUE           135
#endif
#endif
