#if !defined(AFX_TOGGLE_H__04096D51_7B6D_4F1A_9B68_CAF18A8DE491__INCLUDED_)
#define AFX_TOGGLE_H__04096D51_7B6D_4F1A_9B68_CAF18A8DE491__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CToggle wrapper class

class CToggle : public CWnd
{
protected:
	DECLARE_DYNCREATE(CToggle)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x999ea2c3, 0xf93f, 0x11cf, { 0xa4, 0xa, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetBevelInner();
	void SetBevelInner(long);
	long GetBevelOuter();
	void SetBevelOuter(long);
	short GetBevelWidth();
	void SetBevelWidth(short);
	long GetBlinkMode();
	void SetBlinkMode(long);
	short GetBlinkRate();
	void SetBlinkRate(short);
	short GetBorderWidth();
	void SetBorderWidth(short);
	BOOL GetMouseControl();
	void SetMouseControl(BOOL);
	unsigned long GetOffBackColor();
	void SetOffBackColor(unsigned long);
	CString GetOffCaption();
	void SetOffCaption(LPCTSTR);
	unsigned long GetOffForeColor();
	void SetOffForeColor(unsigned long);
	CString GetOffWave();
	void SetOffWave(LPCTSTR);
	short GetOffX();
	void SetOffX(short);
	unsigned long GetOnBackColor();
	void SetOnBackColor(unsigned long);
	CString GetOnCaption();
	void SetOnCaption(LPCTSTR);
	unsigned long GetOnForeColor();
	void SetOnForeColor(unsigned long);
	short GetOnTimer();
	void SetOnTimer(short);
	CString GetOnWave();
	void SetOnWave(LPCTSTR);
	short GetOnX();
	void SetOnX(short);
	short GetOnY();
	void SetOnY(short);
	BOOL GetOutline();
	void SetOutline(BOOL);
	unsigned long GetOutlineColor();
	void SetOutlineColor(unsigned long);
	short GetPushX();
	void SetPushX(short);
	short GetPushY();
	void SetPushY(short);
	BOOL GetSound();
	void SetSound(BOOL);
	BOOL GetValue();
	void SetValue(BOOL);
	BOOL Get_Value();
	void Set_Value(BOOL);
	long GetMode();
	void SetMode(long);
	CPicture GetOffPicture();
	void SetOffPicture(LPDISPATCH);
	CPicture GetOnPicture();
	void SetOnPicture(LPDISPATCH);
	CPicture GetPushPicture();
	void SetPushPicture(LPDISPATCH);
	short GetOffY();
	void SetOffY(short);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetFontBold();
	void SetFontBold(BOOL);
	BOOL GetFontItalic();
	void SetFontItalic(BOOL);
	CString GetFontName();
	void SetFontName(LPCTSTR);
	float GetFontSize();
	void SetFontSize(float);
	BOOL GetFontStrikethru();
	void SetFontStrikethru(BOOL);
	BOOL GetFontUnderline();
	void SetFontUnderline(BOOL);
	BOOL GetSingleBuffer();
	void SetSingleBuffer(BOOL);
	BOOL GetFocusOutline();
	void SetFocusOutline(BOOL);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	CString GetConfiguration();
	void SetConfiguration(LPCTSTR);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	CString GetOutlineTitle();
	void SetOutlineTitle(LPCTSTR);
	short GetOutlineWidth();
	void SetOutlineWidth(short);
	long GetOutlineAlign();
	void SetOutlineAlign(long);

// Operations
public:
	void ShowPropertyPage();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TOGGLE_H__04096D51_7B6D_4F1A_9B68_CAF18A8DE491__INCLUDED_)
